import {colors} from "../themes/color";

export const app_structure_data = [
    /*{
      title: "Invata",
      color: colors.green,
      image: require("../assets/Panda7.png"),
      games: [
        {
          name: "Litere",
          color: colors.red,
          game:"Recunoastere",
          field:"animal",
          progress_rate:20,
        },
        {
          name: "Cifre",
          color: colors.green,
          game:"Recunoastere",
          field:"animal",
          progress_rate:20,
        },
      ],
    },*/
    {
      title: "Recunoastere",
      color: colors.red,
      image: require("../assets/Panda6.png"),
      games: [
        {
          name:"Animale",
          color:colors.red,
          game:"Recunoastere",
          field:"animal",
          progress_rate:20,
          game_xp:10,
          image: require("../assets/animale.png"),
        },
        {
          name: "Fructe",
          color: colors.green,
          game:"Recunoastere",
          field:"fruct",
          progress_rate:20,
          game_xp:10,
          image: require("../assets/fructe.png"),
        },
        {
          name: "Legume",
          color: colors.blue,
          game:"Recunoastere",
          field:"leguma",
          progress_rate:20,
          game_xp:10,
          image: require("../assets/legume.png"),
        },
        {
          name: "Vehicule",
          color: colors.red,
          game:"Recunoastere",
          field:"vehicul",
          progress_rate:20,
          game_xp:10,
          image: require("../assets/vehicule.png"),
        },
        {
          name: "Cifre",
          color: colors.orange,
          game:"Recunoastere",
          field:"cifra",
          progress_rate:20,
          game_xp:10,
          image: require("../assets/cifre.png"),
        },
        {
          name: "Culori",
          color: colors.green,
          game:"Recunoastere",
          field:"culoare",
          progress_rate:20,
          game_xp:10,
          image: require("../assets/culori.png"),
        },
        
      ],
    },
    {
      title: "Selecteaza",
      color: colors.orange,
      image: require("../assets/Panda3.png"),
      games: [
        {
          name: "Perechi de litere",
          color: colors.red,
          game:"LitereMariMici",
          progress_rate:12.5,
          game_xp:5,
          image: require("../assets/Panda6.png"),
        },
        {
          name: "Selectare vocale",
          color: colors.orange,
          game:"SelectareVocale",
          progress_rate:20,
          game_xp:5,
          image: require("../assets/Panda6.png"),
        },
        {
          name: "Sorteaza ",
          color: colors.blue,
          game:"SorteazaCategorii",
          progress_rate:20,
          game_xp:15,
          image: require("../assets/Panda6.png"),
        },
      ],
    },
    {
      title: "Scrie Imaginea",
      color: colors.blue,
      image: require("../assets/Panda5.png"),
      games: [
        {
          name: "Scrie animalul",
          color: colors.red,
          game:"ScriereImagine",
          progress_rate:20,
          field:"animal",
          game_xp:15,
          image: require("../assets/animale.png"),
        },
        {
          name: "Scrie fructele",
          color: colors.green,
          game:"ScriereImagine",
          progress_rate:20,
          field:"fruct",
          game_xp:15,
          image: require("../assets/fructe.png"),
        },
        {
          name: "Scrie legumele",
          color: colors.blue,
          game:"ScriereImagine",
          progress_rate:20,
          field:"leguma",
          game_xp:15,
          image: require("../assets/legume.png"),
        }, 
        {
          name: "Scrie vehiculele",
          color: colors.red,
          game:"ScriereImagine",
          progress_rate:20,
          field:"vehicul",
          game_xp:15,
          image: require("../assets/vehicule.png"),
        },
        {
          name: "Scrie cifrele",
          color: colors.yellow,
          game:"ScriereImagine",
          progress_rate:20,
          field:"cifra",
          game_xp:15,
          image: require("../assets/cifre.png"),
        },
        {
          name: "Scrie culorile",
          color: colors.green,
          game:"ScriereImagine",
          progress_rate:20,
          field:"culoare",
          game_xp:15,
          image: require("../assets/culori.png"),
        },
      ],
    },
    {
      title: "Gaseste",
      color: colors.brown,
      image: require("../assets/Panda7.png"),
      games: [
        {
          name: "Animale ",
          color: colors.green,
          game:"GasesteCategoria",
          field:"animal",
          progress_rate:20,
          game_xp:20,
          image: require("../assets/animale.png"),
        },
        {
          name: "Fructe ",
          color: colors.blue,
          game:"GasesteCategoria",
          field:"fruct",
          progress_rate:20,
          game_xp:20,
          image: require("../assets/fructe.png"),
        },
        {
          name: "Legume ",
          color: colors.purple,
          game:"GasesteCategoria",
          field:"leguma",
          progress_rate:20,
          game_xp:20,
          image: require("../assets/legume.png"),
        },
        {
          name: "Vehicule ",
          color: colors.orange,
          game:"GasesteCategoria",
          field:"vehicul",
          progress_rate:20,
          game_xp:20,
          image: require("../assets/vehicule.png"),
        },
        {
          name: "Cifre ",
          color: colors.red,
          game:"GasesteCategoria",
          field:"cifra",
          progress_rate:20,
          game_xp:20,
          image: require("../assets/cifre.png"),
        },
        {
          name: "Culori ",
          color: colors.brown,
          game:"GasesteCategoria",
          field:"culoare",
          progress_rate:20,
          game_xp:20,
          image: require("../assets/culori.png"),
        },
      ],
    },
  ];