export const inital_data = [
    {name:"LUP",type:"animal", image: "lup.png", description:"Lupul este un mamifer, adică naște pui vii, salbatic care trăiește în pădure. El este carnivor, adică se hrănește cu carne. Este un animal de talie medie, având o greutate de maxim 70 de kg. Lupul trăiește în haită, care este pentru el ca și o familie." },
    {name:"URS",type:"animal", image: "urs.png", description:"Ursul este un mamifer, adică naște pui vii, salbatic care trăiește în pădure. El este carnivor, adică se hrănește cu carne. Este un animal de talie mare, ajungând până la 300 kg. Îi place să doarmă toată iarna, acest lucru se numește hibernare." },
    {name:"VULPE",type:"animal", image: "vulpe.png", description:"Vulpea este un mamifer, adică naște pui vii. Ea trăiește în pădure \n Ceva dupa" },
    {name:"CAL",type:"animal", image: "cal.png", description:"" },
    {name:"VACĂ",type:"animal", image: "vaca.png", description:"" },
    {name:"CÂINE",type:"animal", image: "caine.png", description:"" },
    {name:"PISICĂ",type:"animal", image: "pisica.png", description:"" },
    {name:"ZEBRĂ",type:"animal", image: "zebra.png", description:"" },
    {name:"CAPRĂ",type:"animal", image: "capra.png", description:"" },
    {name:"ȘARPE",type:"animal", image: "sarpe.png", description:"" },
    {name:"CROCODIL",type:"animal", image: "crocodil.png", description:"" },
    {name:"GĂINĂ",type:"animal", image: "gaina.png", description:"" },
    {name:"ȘOARECE",type:"animal", image: "soricel.png", description:"" },
    {name:"CANGUR",type:"animal", image: "cangur.png", description:"" },
    {name:"RINOCER",type:"animal", image: "rinocer.png", description:"" },
    {name:"HIPOPOTAM",type:"animal", image: "hipopotam.png", description:"" },
    {name:"PORUMBEL",type:"animal", image: "porumbel.png", description:"" },
    {name:"BUFNIȚĂ",type:"animal", image: "bufnita.png", description:"" },
    {name:"LEU",type:"animal", image: "leu.png", description:"" },
    {name:"TIGRU",type:"animal", image: "tigru.png", description:"" },
    {name:"KOALA",type:"animal", image: "koala.png", description:"" },
    {name:"PANDA",type:"animal", image: "panda.png", description:"" },
    {name:"ARICI",type:"animal", image: "arici.png", description:"" },
    {name:"CĂMILĂ",type:"animal", image: "camila.png", description:"" },
    {name:"VEVERIȚĂ",type:"animal", image: "veverita.png", description:"" },
    {name:"MISTREȚ",type:"animal", image: "mistret.png", description:"" },
    {name:"CERB",type:"animal", image: "cerb.png", description:"" },
    {name:"MAIMUȚĂ",type:"animal", image: "maimuta.png", description:"" },
    {name:"ELEFANT",type:"animal", image: "elefant.png", description:"" },
    {name:"GIRAFĂ",type:"animal", image: "girafa.png", description:"" },
    {name:"GORILĂ",type:"animal", image: "gorila.png", description:"" },
    {name:"ȚESTOASĂ",type:"animal", image: "testoasa.png", description:"" },
    {name:"BROASCĂ",type:"animal", image: "broasca.png", description:"" },
    {name:"MĂGAR",type:"animal", image: "magar.png", description:"" },
    {name:"OAIE",type:"animal", image: "oaie.png", description:"" },
    {name:"RAȚĂ",type:"animal", image: "rata.png", description:"" },
    {name:"COCOȘ",type:"animal", image: "cocosul.png", description:"" },
    {name:"IEPURE",type:"animal", image: "iepure.png", description:"" },
    {name:"GHEPARD",type:"animal", image: "ghepard.png", description:"" },

    {name:"MĂR",type:"fruct", image: "mar.png", description:"" },
    {name:"PARĂ",type:"fruct", image: "para.png", description:"" },
    {name:"PRUNĂ",type:"fruct", image: "pruna.png", description:"" },
    {name:"PIERSICĂ",type:"fruct", image: "piersica.png", description:"" },
    {name:"CAISĂ",type:"fruct", image: "caisa.png", description:"" },
    {name:"ANANAS",type:"fruct", image: "ananas.png", description:"" },
    {name:"PORTOCALĂ",type:"fruct", image: "portocala.png", description:"" },
    {name:"BANANĂ",type:"fruct", image: "banana.png", description:"" },
    {name:"KIWI",type:"fruct", image: "kiwi.png", description:"" },
    {name:"POMELO",type:"fruct", image: "pomelo.png", description:"" },
    {name:"CIREȘE",type:"fruct", image: "cirese.png", description:"" },
    {name:"CĂPȘUNI",type:"fruct", image: "capsuni.png", description:"" },
    {name:"ZMEURĂ",type:"fruct", image: "zmeura.png", description:"" },
    {name:"MURE",type:"fruct", image: "mure.png", description:"" },
    {name:"LĂMÂIE",type:"fruct", image: "lamaie.png", description:"" },
    {name:"PEPENE",type:"fruct", image: "pepene.png", description:"" },
    {name:"STRUGURI",type:"fruct", image: "struguri.png", description:"" },
    {name:"MANGO",type:"fruct", image: "mango.png", description:"" },
    {name:"AFINE",type:"fruct", image: "afine.png", description:"" },
    {name:"RODIE",type:"fruct", image: "rodie.png", description:"" },
    {name:"COCOS",type:"fruct", image: "cocos.png", description:"" },

    {name:"ROȘIE",type:"leguma", image: "rosie.png", description:"" },
    {name:"MORCOV",type:"leguma", image: "morcov.png", description:"" },
    {name:"ARDEI",type:"leguma", image: "ardei.png", description:"" },
    {name:"CASTRAVETE",type:"leguma", image: "castravete.png", description:"" },
    {name:"CARTOF",type:"leguma", image: "cartof.png", description:"" },
    {name:"CEAPA",type:"leguma", image: "ceapa.png", description:"" },
    {name:"USTUROI",type:"leguma", image: "usturoi.png", description:"" },

    {name:"MAȘINĂ",type:"vehicul", image: "masina.png", description:"" },
    {name:"TREN",type:"vehicul", image: "tren.png", description:"" },
    {name:"AUTOBUZ",type:"vehicul", image: "autobuz.png", description:"" },
    {name:"TIR",type:"vehicul", image: "tir.png", description:"" },
    {name:"MOTOCICLETĂ",type:"vehicul", image: "motocicleta.png", description:"" },
    {name:"BICICLETĂ",type:"vehicul", image: "bicicleta.png", description:"" },
    {name:"TROTINETĂ",type:"vehicul", image: "trotineta.png", description:"" },
    {name:"AVION",type:"vehicul", image: "avion.png", description:"" },

    {name:"ROȘU",type:"culoare", image: "rosu.png", description:"" },
    {name:"PORTOCALIU",type:"culoare", image: "portocaliu.png", description:"" },
    {name:"ALBASTRU",type:"culoare", image: "albastru.png", description:"" },
    {name:"VERDE",type:"culoare", image: "verde.png", description:"" },
    {name:"GALBEN",type:"culoare", image: "galben.png", description:"" },
    {name:"MOV",type:"culoare", image: "mov.png", description:"" },
    {name:"ROZ",type:"culoare", image: "roz.png", description:"" },
    {name:"MARO",type:"culoare", image: "maro.png", description:"" },

    
    {name:"UNU",type:"cifra", image: "NumberOne.png", description:"" },
    {name:"DOI",type:"cifra", image: "NumberTwo.png", description:"" },
    {name:"TREI",type:"cifra", image: "NumberThree.png", description:"" },
    {name:"PATRU",type:"cifra", image: "NumberFour.png", description:"" },
    {name:"CINCI",type:"cifra", image: "NumberFive.png", description:"" },
    {name:"ȘASE",type:"cifra", image: "NumberSix.png", description:"" },
    {name:"ȘAPTE",type:"cifra", image: "NumberSeven.png", description:"" },
    {name:"OPT",type:"cifra", image: "NumberEight.png", description:"" },
    {name:"NOUĂ",type:"cifra", image: "NumberNine.png", description:"" },
    {name:"ZERO",type:"cifra", image: "NumberZero.png", description:"" },


]
